### ISSUE TITLE
Build fails on Fedora 25 (GCC 6.3.1)

### ISSUE THREAD

**Issue by mhoes** [hercules-390/SoftFloat-3a#3]
On Fedora 25 (GCC 6.3.1), I get the following build error when trying to build SoftFloat-3a:

$ cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../../SoftFloat-3a
<- snip ->
$ make -j1
Scanning dependencies of target SoftFloat
[  0%] Building C object CMakeFiles/SoftFloat.dir/source/s_add128.c.o
/home/maarten/src/hyperion-topdir/SoftFloat-3a/source/s_add128.c:48:2: error: return type is an incomplete type
  softfloat_add128( uint64_t a64, uint64_t a0, uint64_t b64, uint64_t b0 )
  ^~~~~~~~~~~~~~~~
/home/maarten/src/hyperion-topdir/SoftFloat-3a/source/s_add128.c: In function ‘softfloat_add128’:
/home/maarten/src/hyperion-topdir/SoftFloat-3a/source/s_add128.c:50:20: error: storage size of ‘z’ isn’t known
     struct uint128 z;
                    ^
/home/maarten/src/hyperion-topdir/SoftFloat-3a/source/s_add128.c:54:12: warning: ‘return’ with a value, in function returning void
     return z;
            ^
/home/maarten/src/hyperion-topdir/SoftFloat-3a/source/s_add128.c:48:2: note: declared here
  softfloat_add128( uint64_t a64, uint64_t a0, uint64_t b64, uint64_t b0 )
  ^~~~~~~~~~~~~~~~
CMakeFiles/SoftFloat.dir/build.make:62: recipe for target 'CMakeFiles/SoftFloat.dir/source/s_add128.c.o' failed
make[2]: *** [CMakeFiles/SoftFloat.dir/source/s_add128.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/SoftFloat.dir/all' failed
make[1]: *** [CMakeFiles/SoftFloat.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by srorso** [comment]
Hi Maarten:

Couple of questions:

Have you been able to build SoftFloat 3a For Hercules using CMake start to finish?  It appears that you are using CMake to generate files for a makefile build, and this has not been tested.  

Have you had the opportunity to build SoftFloat 3a For Hercules using an earlier version of GCC?  No need to backlevel what you have, but if you have built on an older GCC, it would be good to know.

Why are you asking CMake to generate makefiles?  Is there something missing from the CMake build process when CMake builds start to finish?

Let us know...thanks!

Best Regards,
Steve Orso

**Comment by mhoes** [comment]
Oh. I've been building it wrong, then. Sorry. Building it like this (like it says in the 'building' file) produces no errors:

$ cmake ../../SoftFloat-3a
$ cmake --build . --clean-first --config Release
$ cmake -P cmake_install.cmake


Sorry for the noise.

**Comment by srorso** [comment]
Hi Maarten:

No apology needed.  By your efforts, we now know that using the makefile generator for SF3a For Hercules does not work--although I cannot explain why.   Your approach seemed reasonable, and I have never tried it.  

Many thanks!

Best Regards,
Steve Orso

**Comment by mhoes** [comment]
Hi,

I haven't build many codebases with cmake, but the few I did used the method of 'cmake -G "Unix Makefiles"', and then used 'make' for compilation/building. I guess the root cause for my misunderstanding here is that I always assumed that 'cmake' was 'only' a Makefile generator (and equivalants of that on other supported platforms), and never realized it was also a 'make' replacement when using 'cmake --build'.

Oh, well. Live and learn.
