### ISSUE TITLE
Softfloat-3a very intermittently returns incorrect flags when compiled on non-C99 system with bool #define'd as char type

### ISSUE THREAD

**Issue by srorso** [hercules-390/SoftFloat-3a#9]
In test case bfp-021-multadd.tst, the Floating Point Control register flag Inexact is not set correctly for the following calculation, performed in 64-bit precision, when `bool` is `#define`'d as `char`.  The calculation is correct when the `#define` is for `short int` or longer.  
```
*
* Underflow from product of normals.  We will multiply a small normal
* by 0.25 to generate a subnormal.  We cannot add another normal
* (positive or negative) and keep the result subnormal, so we will just
* add a subnormal.  
*
         DC    X'001FFFFFFFFFFFFF'  Very small normal number
         DC    X'3FD0000000000000'  0.25, creates subnormal
         DC    X'0000000000000001'  +Dmin, will appear in result
```
The incremented flag is set as expected.  If incremented is set, inexact should always be set.  

This issue was encountered when experimenting with header coding for Hyperion and SoftFloat-3a that would allow a binary SoftFloat-3a package created on a C99-capable system to be used by a Hyperion built on a non-C99 system.  Because there is no requirement in C99 to implement `bool` in a one-byte space, there are no guarantees of interoperability, but `char` would seem to be a sensible choice for a compiler implementer and therefor the best planning case for portable coding.  

(It has been demonstrated that Hyperion compiled with `#define bool char` will work with a SoftFloat-3a compiled on a C99 system.  But when both are compiled with `#define bool char`, the above calculation fails.)

The error appears to be based in an implicit cast of the intermediate result's rounding bits from 16-bit integer to a `bool` that has been `#define`'d as `char` in the routine `softfloat_roundPackToF64()` modified for Hyperion.  When the rounding bits have zeros in the low-order eight bits, the cast causes the inexact condition to be lost.  

The incorrect code is a part of the modifications to SoftFloat-3a for Hercules and does not exist in the original package.  

The implicit cast exists in `softfloat_roundPackToF32()`, `softfloat_roundPackToF64()`, and `softfloat_roundPackToF128()`.  32-bit calculations are not affected by this coding because the rounding bits are always less than 127 (0x7f).  While only one result in the roughly 30,000 calculations was incorrect, this issue has the potential to affect any IBM Binary Floating Point operation that:

 1. returns a floating point result,
 2. generates a trappable underflow or overflow, and
 3. the scaled result is inexact.

The correction is to change the assignment in each routine so that the result of a logical expression is assigned to the `char` used as a `bool`.  For example,
```
  softfloat_raw.Inexact = roundBits;       /* Save inexact status of raw result        */
```
must become:
```
  softfloat_raw.Inexact = roundBits != 0;   /* Save inexact status of raw result        */
```
All three routines should be changed for consistency even though the domain of `roundBits` in 32-bit calculations prevents the issue.

**Comment by peterfirefly** [comment]
!!x is a standard trick to normalize the boolean value of an integer to 0/1.
